### ISSUE TITLE
Can't set timezone in container

### ISSUE THREAD

**Issue by DirkDuesentrieb** [netdisco/netdisco-docker#46]
Hi,
I'd like to adjust the timezone settings. Normally passing _TZ=Europe/Berlin_ to docker as environment does the trick for Alpine based images. But it seems the **tzdata** package is missing in the netdisco-base image.
Can you add the package, or provide a different method please?

Thanks,

Dirk

**Comment by rc9000** [comment]
I gave this a try, but it looks like besides TZ in docker-compose.yml, I also needed to set the server timezone in postgresql.conf - otherwise it's hardcoded to UTC there.

    ~/nd2_docker/netdisco/pgdata# grep -i zurich postgresql.conf 
    timezone = 'Europe/Zurich'

Afterwards, it looked like all my timestamps were successfully displayed and stored as CET. Maybe you can give this a shot once our release to dockerhub went through? It could certainly use some more testing.

PS for the docker-compose side, I added TZ exactly as you propose, in all the containers. E.g.

```
  netdisco-backend:
    .... 
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
      TZ: Europe/Zurich
```
