### ISSUE TITLE
netdisco-web fails

### ISSUE THREAD

**Issue by gustavoberman** [netdisco/netdisco-docker#51]
## Expected Behavior

access web interface at port 5000

## Current Behavior

web interface is unavailable

## Steps to Reproduce (for bugs)

1. Follow installation instructions from https://hub.docker.com/r/netdisco/netdisco
```
[root@www netdisco]# docker compose up
[+] Running 4/4
 ⠿ Network netdisco_default                  Created                                            0.4s
 ⠿ Container netdisco-netdisco-postgresql-1  Crea...                                            1.7s
 ⠿ Container netdisco-netdisco-backend-1     Created                                            3.0s
 ⠿ Container netdisco-netdisco-web-1         Created                                            2.9s
Attaching to netdisco-netdisco-backend-1, netdisco-netdisco-postgresql-1, netdisco-netdisco-web-1
netdisco-netdisco-postgresql-1  | The files belonging to this database system will be owned by user "postgres".
netdisco-netdisco-postgresql-1  | This user must also own the server process.
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | The database cluster will be initialized with locale "en_US.utf8".
netdisco-netdisco-postgresql-1  | The default database encoding has accordingly been set to "UTF8".
netdisco-netdisco-postgresql-1  | The default text search configuration will be set to "english".
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | Data page checksums are disabled.
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
netdisco-netdisco-postgresql-1  | creating subdirectories ... ok
netdisco-netdisco-postgresql-1  | selecting dynamic shared memory implementation ... posix
netdisco-netdisco-postgresql-1  | selecting default max_connections ... 100
netdisco-netdisco-postgresql-1  | selecting default shared_buffers ... 128MB
netdisco-netdisco-postgresql-1  | selecting default time zone ... UTC
netdisco-netdisco-postgresql-1  | creating configuration files ... ok
netdisco-netdisco-postgresql-1  | running bootstrap script ... ok
netdisco-netdisco-backend-1     | Attempting to create directory /home/netdisco/perl5
netdisco-netdisco-web-1         | Attempting to create directory /home/netdisco/perl5
netdisco-netdisco-postgresql-1  | performing post-bootstrap initialization ... sh: locale: not found
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:19.468 UTC [36] WARNING:  no usable system locales were found
netdisco-netdisco-backend-1     | config watcher: watching /home/netdisco/environments for updates.
netdisco-netdisco-web-1         | config watcher: watching /home/netdisco/environments for updates.
netdisco-netdisco-web-1         | 2022/12/14-12:30:20 Starman::Server (type Net::Server::PreFork) starting! pid(7)
netdisco-netdisco-web-1         | Resolved [*]:5000 to [::]:5000, IPv6
netdisco-netdisco-web-1         | Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
netdisco-netdisco-web-1         | Binding to TCP port 5000 on host :: with IPv6
netdisco-netdisco-web-1         | 2022/12/14-12:30:20 Can't connect to TCP port 5000 on :: [Invalid argument]
netdisco-netdisco-web-1         |   at line 66 in file /home/netdisco/perl5/lib/perl5/Net/Server/Proto/TCP.pm
netdisco-netdisco-web-1         | 2022/12/14-12:30:20 Received QUIT. Running a graceful shutdown
netdisco-netdisco-web-1         | 2022/12/14-12:30:20 Worker processes cleaned up
netdisco-netdisco-web-1         | 2022/12/14-12:30:20 Server closing!
netdisco-netdisco-postgresql-1  | ok
netdisco-netdisco-postgresql-1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
netdisco-netdisco-postgresql-1  | You can change this by editing pg_hba.conf or using the option -A, or
netdisco-netdisco-postgresql-1  | --auth-local and --auth-host, the next time you run initdb.
netdisco-netdisco-postgresql-1  | ok
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | Success. You can now start the database server using:
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | waiting for server to start....2022-12-14 12:30:22.820 UTC [42] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:23.235 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:23.259 UTC [43] LOG:  database system was shut down at 2022-12-14 12:30:20 UTC
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:23.293 UTC [42] LOG:  database system is ready to accept connections
netdisco-netdisco-postgresql-1  |  done
netdisco-netdisco-postgresql-1  | server started
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/netdisco-initdb.sh
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: configuring Netdisco user and db
netdisco-netdisco-postgresql-1  | CREATE ROLE
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: restarting pg privately to container
netdisco-netdisco-postgresql-1  | waiting for server to shut down....2022-12-14 12:30:24.511 UTC [42] LOG:  received fast shutdown request
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.539 UTC [42] LOG:  aborting any active transactions
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.540 UTC [42] LOG:  background worker "logical replication launcher" (PID 49) exited with exit code 1
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.540 UTC [44] LOG:  shutting down
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.624 UTC [42] LOG:  database system is shut down
netdisco-netdisco-postgresql-1  |  done
netdisco-netdisco-postgresql-1  | server stopped
netdisco-netdisco-postgresql-1  | waiting for server to start....2022-12-14 12:30:24.752 UTC [60] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.752 UTC [60] LOG:  listening on IPv4 address "127.0.0.1", port 5432
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.752 UTC [60] LOG:  could not bind IPv6 address "::1": Address not available
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.752 UTC [60] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.849 UTC [60] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.891 UTC [61] LOG:  database system was shut down at 2022-12-14 12:30:24 UTC
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:24.938 UTC [60] LOG:  database system is ready to accept connections
netdisco-netdisco-postgresql-1  |  done
netdisco-netdisco-postgresql-1  | server started
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: bringing schema up-to-date
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: importing OUI
netdisco-netdisco-postgresql-1  | COPY 31042
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: marking schema as up-to-date
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: adding admin user if none exists
netdisco-netdisco-postgresql-1  | INSERT 0 1
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: adding session key if none exists
netdisco-netdisco-postgresql-1  | INSERT 0 1
netdisco-netdisco-postgresql-1  | netdisco-db-entrypoint: queueing stats job
netdisco-netdisco-postgresql-1  | INSERT 0 1
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | waiting for server to shut down....2022-12-14 12:30:29.835 UTC [60] LOG:  received fast shutdown request
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:29.872 UTC [60] LOG:  aborting any active transactions
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:29.872 UTC [60] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:29.873 UTC [62] LOG:  shutting down
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.459 UTC [60] LOG:  database system is shut down
netdisco-netdisco-postgresql-1  |  done
netdisco-netdisco-postgresql-1  | server stopped
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | PostgreSQL init process complete; ready for start up.
netdisco-netdisco-postgresql-1  | 
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.601 UTC [1] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.601 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.601 UTC [1] LOG:  listening on IPv6 address "::", port 5432
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.662 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.705 UTC [324] LOG:  database system was shut down at 2022-12-14 12:30:30 UTC
netdisco-netdisco-postgresql-1  | 2022-12-14 12:30:30.715 UTC [1] LOG:  database system is ready to accept connections

```
## Context

Initial install and run

## Your Environment

* netdisco container versions: 
  * netdisco-postgresql: latest-postgresql 2.060002
  * netdisco-backend: latest-backend 2.060002
  * netdisco-web: latest-web 2.060002
* docker engine version: docker-ce-20.10.21-3.el7.x86_64
* docker-compose version: docker-compose-plugin-2.12.2-3.el7.x86_64
* host operating system: RHEL 7.9

## Config info (deployment.yml and docker env settings)

```
[root@www netdisco]# cat docker-compose.yml 
version: '2.3'
services:

  netdisco-postgresql:
    image: netdisco/netdisco:latest-postgresql
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
      
  netdisco-backend:
    image: netdisco/netdisco:latest-backend
    volumes:
      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
      - "./netdisco/config:/home/netdisco/environments"
      - "./netdisco/logs:/home/netdisco/logs"
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
    dns_opt:
      - 'ndots:0'
      - 'timeout:1'
      - 'retries:0'
      - 'attempts:1'
      - edns0
      - trustad

  netdisco-web:
    image: netdisco/netdisco:latest-web
    volumes:
      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
      - "./netdisco/config:/home/netdisco/environments"
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    ports:
      - "5000:5000"
    depends_on:
      - netdisco-postgresql
    dns_opt:
      - 'ndots:0'
      - 'timeout:1'
      - 'retries:0'
      - 'attempts:1'
      - edns0
      - trustad
      
  netdisco-do:
    image: netdisco/netdisco:latest-do
    volumes:
      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
      - "./netdisco/config:/home/netdisco/environments"
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
    profiles:
      - cli-manual

```
