### ISSUE TITLE
Netdisco DB Password - How do you change this?

### ISSUE THREAD

**Issue by G0nz0uk** [netdisco/netdisco-docker#80]
Hello,

I'm using Netdisco in Docker Compose, it's great.

I've spend ages looking, but could you tell me how I can change the default password for the postgresdb please as seen in the deployment.yml file, it's set to 'pass: 'netdisco'

```
# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdisco'
  user: 'netdisco'
  pass: 'netdisco'
```

As seen in here too:

https://github.com/netdisco/netdisco-docker/blob/master/netdisco-postgresql/netdisco-updatedb.sh

Thanks
